#!/bin/bash

echo "=== Oh My OpenCode Setup Script ==="
echo ""
echo "Step 1: Authenticate with GitHub Copilot"
echo "Run this command and select 'GitHub Copilot' -> 'Authenticate via OAuth':"
echo "opencode auth login"
echo ""
echo "Step 2: Verify Setup"
echo "After authentication, run: opencode --version"
echo ""
echo "Step 3: Start Using Oh My OpenCode!"
echo "Simply run: opencode"
echo ""
echo "=== Configuration Complete ==="
echo "Plugin: oh-my-opencode"
echo "Main Agent: Sisyphus (GitHub Copilot Claude Opus 4.5)"
echo "Specialized Agents: oracle, librarian, explore, etc."
echo ""
echo "=== Pro Tips ==="
echo "- Include 'ultrawork' or 'ulw' in prompts for maximum performance"
echo "- Use @oracle for architecture review, @librarian for documentation lookup"
echo "- Background agents run automatically for complex tasks"
echo ""
echo "Congratulations! 🎉 You have successfully set up OhMyOpenCode!"